apiVersion: batch/v1
kind: Job
metadata:
    name: freejob
spec:
    template:
        spec:
            containers:
            - name: dockerimg
              image: radar8/mp12classifier:mp12-python
              env:
                - name: DATASET
                  value: "mnist"
                - name: TYPE
                  value: "ff"
            restartPolicy: Never